#!/bin/bash
set -eu

# Install system requirements: git, direnv, docker
sudo apt-get update 
sudo apt-get install -y \
    git \
    direnv \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

# Install docker debian repository
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
sudo apt-get update

# Install docker
sudo apt-get install -y \
     docker-ce \
     docker-ce-cli \
     containerd.io

# Install docker-compose
sudo curl -L \
    "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" \
    -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Hook direnv into the shell
echo 'eval "$(direnv hook bash)"' >>~/.bashrc

# Check out the application (seanharrison/urlly)
git clone https://github.com/seanharrison/urlly
cd urlly

# Create .envrc with all the necessary values
cp _envrc.TEMPLATE.sh .envrc
echo "export POSTGRES_PASSWORD=$(openssl rand -hex 32)" >>.envrc
echo "autogenerated a POSTGRES_PASSWORD to .envrc"

# Instructions for finishing setup and deployment
cat DEPLOY.md
