"""urls

Revision ID: 4833c7a7644f
Revises: 
Create Date: 2020-11-21 21:47:56.979788

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4833c7a7644f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("urls")
    # ### end Alembic commands ###
